### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by RaphaelHarm** [RaphaelHarm/Unity-J-R#1]
Aufbau des Projekts entscheiden.
Ergebnisse als Kommentar hinzufügen.

**Comment by ZmaxZboss** [comment]
Jump and Run 3D

**Comment by VictoriousSecretModel** [comment]
Verschiedene Platformen z.B. bewegende und drehende Platformen

**Comment by ZmaxZboss** [comment]
Normale Bewegungen, Springen

**Comment by ZmaxZboss** [comment]
Teleporter, Türen

**Comment by ZmaxZboss** [comment]
Teleporter, Türen

**Comment by Joooohannes** [comment]
Doppelsprünge, Hindernisse, Gegner

**Comment by ZmaxZboss** [comment]
> Doppelsprünge, Hindernisse, Gegner

Vorschlag.: Doppelsprünge/Gegner erst im "Advance Game"

**Comment by RaphaelHarm** [comment]
> 
> 
> Doppelsprünge, Hindernisse, Gegner

Gegner als bewegliche Hindernisse

**Comment by ZmaxZboss** [comment]
> Doppelsprünge, Hindernisse, Gegner

Doppelsprünge erst wenn wir springen hingekriegt haben?

**Comment by ZmaxZboss** [comment]
Unterschiedliche Welten z.B.: Lobby, JumpAndRun_LvL1

**Comment by RaphaelHarm** [comment]
![CameraMovement](https://user-images.githubusercontent.com/77887630/106360626-cf688d80-6319-11eb-95f9-5e5edf5b1c55.png)

**Comment by RaphaelHarm** [comment]
closed
